DELETE FROM Flight;
DELETE FROM Spacecraft;
DELETE FROM Planet;
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (1,  'Terra',   1, 'mild',          0, 6371);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (2,  'Aquara',  1, 'warm',          1, 7000);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (3,  'Pyros',   0, 'hot',           1, 3200);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (4,  'Glacia',  0, 'cold',          0, 5200);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (5,  'Verda',   1, 'mild',          1, 6800);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (6,  'Dunar',   0, 'warm',          0, 4500);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (7,  'Solmar',  0, 'hot',           0, 9800);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (8,  'Mirren',  1, 'extremely hot', 0, 8200);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (9,  'Cobar',   0, 'mild',          0, 7100);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (10, 'Frost',   0, 'cold',          1, 5000);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (12, 'Zephyra', 0, 'warm',          0, 12000);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (42, 'Answer',  1, 'mild',          0, 4242);
INSERT INTO Spacecraft(id, name, capacity) VALUES (1, 'Falcon 22', 5);
INSERT INTO Spacecraft(id, name, capacity) VALUES (2, 'Falcon 25', 3);
INSERT INTO Spacecraft(id, name, capacity) VALUES (3, 'Falcon 28', 7);
INSERT INTO Flight(num, planet_id, flight_date, spacecraft_id, people_count) VALUES ('AF201', 1,  '2122-04-12', 1, 5);
INSERT INTO Flight(num, planet_id, flight_date, spacecraft_id, people_count) VALUES ('AF147', 5,  '2122-05-01', 3, 4);
INSERT INTO Flight(num, planet_id, flight_date, spacecraft_id, people_count) VALUES ('AF149', 5,  '2122-05-08', 2, 3);
INSERT INTO Flight(num, planet_id, flight_date, spacecraft_id, people_count) VALUES ('AF210', 2,  '2122-05-12', 1, 2);
INSERT INTO Flight(num, planet_id, flight_date, spacecraft_id, people_count) VALUES ('AF305', 42, '2122-06-01', 3, 7);
INSERT INTO Flight(num, planet_id, flight_date, spacecraft_id, people_count) VALUES ('AF088', 3,  '2122-06-15', 2, 1);
