DELETE FROM Flight;
DELETE FROM Spacecraft;
DELETE FROM Planet;
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (1,  'Terra',   1, 'mild',          0, 6371);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (2,  'Aquara',  1, 'warm',          1, 7000);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (3,  'Pyros',   0, 'hot',           1, 3200);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (4,  'Glacia',  0, 'cold',          0, 5200);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (5,  'Verda',   1, 'mild',          1, 6800);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (6,  'Dunar',   0, 'warm',          0, 4500);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (7,  'Solmar',  0, 'hot',           0, 9800);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (8,  'Mirren',  1, 'extremely hot', 0, 8200);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (9,  'Cobar',   0, 'mild',          0, 7100);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (10, 'Frost',   0, 'cold',          1, 5000);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (12, 'Zephyra', 0, 'warm',          0, 12000);
INSERT INTO Planet(id, name, is_inhabited, climate, has_weapons, radius) VALUES (42, 'Answer',  1, 'mild',          0, 4242);
INSERT INTO Spacecraft(id, name, capacity) VALUES (1, 'Falcon 22', 5);
INSERT INTO Spacecraft(id, name, capacity) VALUES (2, 'Falcon 25', 3);
INSERT INTO Spacecraft(id, name, capacity) VALUES (3, 'Falcon 28', 7);
INSERT INTO Spacecraft(id, name, capacity) VALUES (4, 'Pegasus',   12);
INSERT INTO Spacecraft(id, name, capacity) VALUES (5, 'Comet 9',   8);
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (1,  'AF201', 1,  '2122-04-12', 1, 5,  'ore');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (2,  'AF147', 5,  '2122-05-01', 3, 4,  NULL);
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (3,  'AF149', 5,  '2122-05-08', 2, 3,  'water');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (4,  'AF210', 2,  '2122-05-12', 1, 2,  NULL);
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (5,  'AF305', 42, '2122-06-01', 3, 7,  'seeds');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (6,  'AF088', 3,  '2122-06-15', 2, 1,  'ore');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (7,  'AF412', 1,  '2122-06-20', 4, 8,  'tools');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (8,  'AF413', 1,  '2122-07-02', 4, 10, NULL);
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (9,  'AF414', 2,  '2122-07-05', 4, 6,  'water');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (10, 'AF520', 5,  '2122-07-10', 1, 4,  'ore');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (11, 'AF521', 42, '2122-07-14', 2, 2,  NULL);
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (12, 'AF522', 3,  '2122-07-20', 3, 5,  'fuel');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (13, 'AF530', 5,  '2122-08-01', 4, 9,  'tools');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (14, 'AF531', 1,  '2122-08-03', 1, 3,  'water');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (15, 'AF101', 1,  '2121-03-05', 4, 7, 'ore');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (16, 'AF102', 3,  '2121-04-10', 4, 5, 'fuel');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (17, 'AF103', 5,  '2121-05-20', 4, 8, NULL);
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (18, 'AF104', 2,  '2121-06-12', 4, 6, 'water');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (19, 'AF105', 6,  '2121-04-18', 1, 3, 'ore');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (20, 'AF106', 5,  '2121-07-01', 1, 4, 'seeds');
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (21, 'AF107', 3,  '2121-08-09', 3, 2, NULL);
INSERT INTO Flight(id, num, planet_id, flight_date, spacecraft_id, people_count, cargo) VALUES (22, 'AF108', 8,  '2121-09-15', 4, 9, 'tools');
